/scratch/rd2893/miniconda3/envs/pcgrl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py:32: UserWarning: [33mWARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (16, 16)[0m
  "A Box observation space has an unconventional shape (neither an image, nor a 1D vector). "
2022-11-29 15:05:25,081	WARNING env.py:236 -- Your MultiAgentEnv <MultiAgentWrapper<ControlWrapper<CroppedImagePCGRLWrapper<ToImage<OneHotEncoding<Cropped<OrderEnforcing<PcgrlCtrlEnv<binary-turtle-v0>>>>>>>>> does not have some or all of the needed base-class attributes! Make sure you call `super().__init__` from within your MutiAgentEnv's constructor. This will raise an error in the future.
2022-11-29 15:05:27,854	INFO worker.py:1518 -- Started a local Ray instance.
[2m[36m(PPOTrainer pid=1434787)[0m 2022-11-29 15:05:35,204	INFO ppo.py:379 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
[2m[36m(PPOTrainer pid=1434787)[0m 2022-11-29 15:05:35,205	INFO algorithm.py:358 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[2m[36m(PPOTrainer pid=1434787)[0m /scratch/rd2893/miniconda3/envs/pcgrl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py:32: UserWarning: [33mWARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (16, 16)[0m
[2m[36m(PPOTrainer pid=1434787)[0m   "A Box observation space has an unconventional shape (neither an image, nor a 1D vector). "
[2m[36m(PPOTrainer pid=1434787)[0m 2022-11-29 15:05:41,952	WARNING deprecation.py:48 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
[2m[36m(PPOTrainer pid=1434787)[0m 2022-11-29 15:05:42,156	WARNING util.py:66 -- Install gputil for GPU system monitoring.
[2m[36m(PPOTrainer pid=1434787)[0m 2022-11-29 15:05:42,261	WARNING deprecation.py:48 -- DeprecationWarning: `policy_mapping_fn(agent_id)` has been deprecated. Use `policy_mapping_fn(agent_id, episode, worker, **kwargs)` instead. This will raise an error in the future!
[2m[36m(PPOTrainer pid=1434787)[0m 2022-11-29 15:05:44,313	WARNING deprecation.py:48 -- DeprecationWarning: `concat_samples` has been deprecated. Use `concat_samples() from rllib.policy.sample_batch` instead. This will raise an error in the future!
[2m[36m(PPOTrainer pid=1434787)[0m /scratch/rd2893/miniconda3/envs/pcgrl/lib/python3.7/site-packages/ray/rllib/utils/metrics/learner_info.py:110: RuntimeWarning: Mean of empty slice
[2m[36m(PPOTrainer pid=1434787)[0m   return np.nanmean(tower_data)
2022-11-30 01:30:35,219	WARNING util.py:244 -- The `callbacks.on_trial_result` operation took 8.386 s, which may be a performance bottleneck.
2022-11-30 01:30:35,220	WARNING util.py:244 -- The `process_trial_result` operation took 8.388 s, which may be a performance bottleneck.
2022-11-30 01:30:35,220	WARNING util.py:244 -- Processing trial results took 8.388 s, which may be a performance bottleneck. Please consider reporting results less frequently to Ray Tune.
2022-11-30 01:30:35,220	WARNING util.py:244 -- The `process_trial_result` operation took 8.389 s, which may be a performance bottleneck.
2022-11-30 01:31:45,292	WARNING util.py:244 -- The `callbacks.on_trial_result` operation took 10.041 s, which may be a performance bottleneck.
2022-11-30 01:31:45,293	WARNING util.py:244 -- The `process_trial_result` operation took 10.042 s, which may be a performance bottleneck.
2022-11-30 01:31:45,296	WARNING util.py:244 -- Processing trial results took 10.046 s, which may be a performance bottleneck. Please consider reporting results less frequently to Ray Tune.
2022-11-30 01:31:45,296	WARNING util.py:244 -- The `process_trial_result` operation took 10.047 s, which may be a performance bottleneck.
submitit WARNING (2022-11-30 15:02:50,940) - Caught signal SIGUSR2 on gv006.hpc.nyu.edu: this job is timed-out.
submitit WARNING (2022-11-30 15:03:01,174) - Bypassing signal SIGCONT
Traceback (most recent call last):
  File "/scratch/rd2893/miniconda3/envs/pcgrl/lib/python3.7/site-packages/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out too many times.
Exception ignored in: 'ray._raylet.check_signals'
Traceback (most recent call last):
  File "/scratch/rd2893/miniconda3/envs/pcgrl/lib/python3.7/site-packages/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out too many times.
slurmstepd: error: *** JOB 27482704 ON gv006 CANCELLED AT 2022-11-30T15:05:22 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 27482704.0 ON gv006 CANCELLED AT 2022-11-30T15:05:22 DUE TO TIME LIMIT ***
*** SIGTERM received at time=1669838722 on cpu 10 ***
PC: @     0x14b4c1a2a64a  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[failure_signal_handler.cc : 331] RAW: Signal 15 raised at PC=0x14b4c17b4627 while already in AbslFailureSignalHandler()
*** SIGTERM received at time=1669838722 on cpu 10 ***
PC: @     0x14b4c17b4627  (unknown)  __strlen_avx2
    @     0x14b4c1a2eb20       5712  (unknown)
    @     0x14b4c16a74f6       1456  _IO_vfprintf
    @     0x14b4c16d0784       1664  __vsnprintf
    @ 0x3462343178302020  (unknown)  (unknown)
[2022-11-30 15:05:22,211 E 1432424 1432424] logging.cc:361: *** SIGTERM received at time=1669838722 on cpu 10 ***
[2022-11-30 15:05:22,211 E 1432424 1432424] logging.cc:361: PC: @     0x14b4c17b4627  (unknown)  __strlen_avx2
[2022-11-30 15:05:22,213 E 1432424 1432424] logging.cc:361:     @     0x14b4c1a2eb20       5712  (unknown)
[2022-11-30 15:05:22,213 E 1432424 1432424] logging.cc:361:     @     0x14b4c16a74f6       1456  _IO_vfprintf
[2022-11-30 15:05:22,213 E 1432424 1432424] logging.cc:361:     @     0x14b4c16d0784       1664  __vsnprintf
[2022-11-30 15:05:22,214 E 1432424 1432424] logging.cc:361:     @ 0x3462343178302020  (unknown)  (unknown)
    @     0x14b4c1a2eb20  (unknown)  (unknown)
[2022-11-30 15:05:22,214 E 1432424 1432424] logging.cc:361: *** SIGTERM received at time=1669838722 on cpu 10 ***
[2022-11-30 15:05:22,214 E 1432424 1432424] logging.cc:361: PC: @     0x14b4c1a2a64a  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-11-30 15:05:22,216 E 1432424 1432424] logging.cc:361:     @     0x14b4c1a2eb20  (unknown)  (unknown)
submitit WARNING (2022-11-30 15:05:22,705) - Bypassing signal SIGTERM
submitit WARNING (2022-11-30 15:05:22,705) - Bypassing signal SIGCONT
